#pragma once

#include <string_view>
#include <vulkan/vulkan_core.h>

#define STR(r) \
    case r:    \
        return #r;
#define ERROR_MAP(r) "error_vk_strmp_" #r;

namespace mcs::vulkan::to_string
{
    static constexpr std::string_view to_string(VkResult v) noexcept
    {
        using enum VkResult;
        switch (v)
        {
            STR(VK_SUCCESS)
            STR(VK_NOT_READY)
            STR(VK_TIMEOUT)
            STR(VK_EVENT_SET)
            STR(VK_EVENT_RESET)
            STR(VK_INCOMPLETE)
            STR(VK_ERROR_OUT_OF_HOST_MEMORY)
            STR(VK_ERROR_OUT_OF_DEVICE_MEMORY)
            STR(VK_ERROR_INITIALIZATION_FAILED)
            STR(VK_ERROR_DEVICE_LOST)
            STR(VK_ERROR_MEMORY_MAP_FAILED)
            STR(VK_ERROR_LAYER_NOT_PRESENT)
            STR(VK_ERROR_EXTENSION_NOT_PRESENT)
            STR(VK_ERROR_FEATURE_NOT_PRESENT)
            STR(VK_ERROR_INCOMPATIBLE_DRIVER)
            STR(VK_ERROR_TOO_MANY_OBJECTS)
            STR(VK_ERROR_FORMAT_NOT_SUPPORTED)
            STR(VK_ERROR_FRAGMENTED_POOL)
            STR(VK_ERROR_UNKNOWN)
            STR(VK_ERROR_OUT_OF_POOL_MEMORY)
            STR(VK_ERROR_INVALID_EXTERNAL_HANDLE)
            STR(VK_ERROR_FRAGMENTATION)
            STR(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS)
            STR(VK_PIPELINE_COMPILE_REQUIRED)
            STR(VK_ERROR_NOT_PERMITTED)
            STR(VK_ERROR_SURFACE_LOST_KHR)
            STR(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR)
            STR(VK_SUBOPTIMAL_KHR)
            STR(VK_ERROR_OUT_OF_DATE_KHR)
            STR(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR)
            STR(VK_ERROR_VALIDATION_FAILED_EXT)
            STR(VK_ERROR_INVALID_SHADER_NV)
            STR(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR)
            STR(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR)
            STR(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR)
            STR(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR)
            STR(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR)
            STR(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR)
            STR(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT)
            STR(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT)
            STR(VK_THREAD_IDLE_KHR)
            STR(VK_THREAD_DONE_KHR)
            STR(VK_OPERATION_DEFERRED_KHR)
            STR(VK_OPERATION_NOT_DEFERRED_KHR)
            STR(VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR)
            STR(VK_ERROR_COMPRESSION_EXHAUSTED_EXT)
            STR(VK_INCOMPATIBLE_SHADER_BINARY_EXT)
            STR(VK_PIPELINE_BINARY_MISSING_KHR)
            STR(VK_ERROR_NOT_ENOUGH_SPACE_KHR)
            STR(VK_RESULT_MAX_ENUM)
        }
        return ERROR_MAP(VkResult);
    }

}; // namespace mcs::vulkan::to_string

#undef STR
#undef ERROR_MAP